name:                linebyline
version:             0.2.8.2
github:              "pylover/linebyline"
license:             BSD3
author:              "Vahid Mardani"
maintainer:          "vahid.mardani@gmail.com"
copyright:           "2022 Vahid Mardani"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/pylover/linebyline#readme>

dependencies:
  - base >= 4.7 && < 5
  - mtl >= 2.2.2 && <2.3
  - transformers >= 0.5.6.2 && <0.6
  - containers >=0.6.4.1 && <0.7
  - regex-tdfa >=1.3.1.2 && <1.4
  - split >= 0.2.3.4

library:
  source-dirs: src

executables:
  lbl:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - linebyline

tests:
  linebyline-test:
    main:                Main
    source-dirs:    
      - test
    other-modules:
      - TestHelpers
      - TestTokenizer
      - TestParser
      - TestEvaluator
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - HTF
      - linebyline
